import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";
import { MainNavbar } from "@/components/atoms";
import { NextAuthSessionProvider } from "@/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
      <body>
        <MainNavbar />
        <main>{children}</main>
      </body>
      </NextAuthSessionProvider>
    </html>
  );
}
